import Head from "next/head";
import { Footer } from "../components/Footer";
import { NavBar } from "../components/NavBar";
import { createClient } from "contentful";

export async function getStaticProps() {
    const client = createClient({
        accessToken: "",
        space: "",
    });

    const res = await client.getEntries({ content_type: "header" });
    return {
        props: {
            image: res.items[0].fields,
        },
    };
}

type Props = {
    image: object;
};

export default function Home({ image }: Props) {
    return (
        <div>
            <Head>
                <title>NJPWDB | Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar image={image} />
            <main></main>
            <Footer />
        </div>
    );
}
